package enigma;
/**
 * The RotorMappings class containing the permutation information of every rotor
 * 
 * @author Daniel Matyas Perendi
 */
public class RotorMappings {


	static final String[][] MAPPINGS = { { "I", "EKMFLGDQVZNTOWYHXUSPAIBRCJ", "UWYGADFPVZBECKMTHXSLRINQOJ", "Q", "English"},
			{ "II", "AJDKSIRUXBLHWTMCQGZNPYFVOE", "AJPCZWRLFBDKOTYUQGENHXMIVS", "E", "English" },
			{ "III", "BDFHJLCPRTXVZNYEIWGAKMUSQO", "TAGBPCSDQEUFVNZHYIXJWLRKOM", "V", "English" },
			{ "IV", "ESOVPZJAYQUIRHXLNFTGKDCMWB", "HZWVARTNLGUPXQCEJMBSKDYOIF", "J", "English" },
			{ "V", "VZBRGITYUPSDNHLXAWMJQOFECK", "QCYLXWENFTZOSMVJUDKGIARPHB", "Z", "English" },
			{ "VI", "JPGVOUMFYQBENHZRDKASXLICTW", "SKXQLHCNWARVGMEBJPTYFDZUIO", "ZM", "English" },
			{ "VII", "NZJHGRCXMYSWBOUFAIVLPEKQDT", "QMGYVPEDRCWTIANUXFKZOSLHJB", "ZM", "English" },
			{ "VIII", "FKQHTLXOCBJSPDZRAMEWNIUYGV", "QJINSAYDVKBFRUHMCPLEWZTGXO", "ZM", "English" },
			{ "BETA", "LEYJVCNIXWPBQMDRTAKZGFUHOS", "RLFOBVUXHDSANGYKMPZQWEJICT", "", "English" },
			{ "GAMMA", "FSOKANUERHMBTIYCWLQPZXVGJD", "ELPZHAXJNYDRKFCTSIBMGWQVOU", "", "English" },
			{ "I", "CFÉQÚPDNŐWÍÁLYTÓBHŰXÜJAKSGMÖVOIRUEZ", "QÍNAÉYBÁTOVIPRJUFŰMÚGECWSLXDŐÓÜHÖKZ", "Q", "Hungarian" },
			{ "II", "HZÚYXDIGOUŰÜKBEJÓANFÖÉÍQŐCRLSÁMWTVP", "OŰKTELPÖFAÉQMJÚVÓGNŐSZRUÜXHBÍIYWDCÁ", "E", "Hungarian" },
			{ "III", "QKWÖEJŐÁMŰÜXÚTGIÓNUACLDHRÍZPBFSYVÉO", "ÖFÜŐQDYŰLRMTEÁPGOZNCÉÚASVKÓJIHXBÍWU", "V", "Hungarian" },
			{ "IV", "INAMCVÜKÖPÁUFÍBHÚTŐÉQXLDJSGÓEYWŰORZ", "BILDRÜÖJUMAKSFQCÁXÚGÓHŐYTOÍNÉWEVPŰZ", "J", "Hungarian" },
			{ "V", "OVUSXÉÍWÖIÚÁEZNLÜŐCQRATPBYJHDMÓKGŰF", "PÍSÓÜJEZXÚHÉUWMŰLAVGORÖŐCQBINYÁFDTK", "Z", "Hungarian" },
			{ "VI", "ÉCKWJLBAGÁIRNHMŰÖŐZPEFÓOTDQUÍSYXÜÚV", "FHÉÁTŐAPGKIÜDBELJRQNOÖUÍŰSÚYXMZCWVÓ", "ZM", "Hungarian" },
			{ "VII", "MTUESRIBAGHWZKCŰPOŐVXÁÖDJQNÍFÚÜÉLYÓ", "GPFLRCWÜHIÉÚSKXAUOZQÓNTEDÁBŰVMÖÍŐYJ", "ZM", "Hungarian" },
			{ "VIII", "CSXBQÚFDEKÜHAORNMIVZTÖPŐJŰWLGÍUÉYÓÁ", "JZCAFGWÉÜÍOŰSHÚNMKYPRQDLÁŐVEITÓUBXÖ", "ZM", "Hungarian" },
			{ "BETA", "CŐÜDKQŰÍYTPOÁÉILÖVSUHGFÓWZJRBAENMXÚ", "ŰJÜACVKQPŐLFUDMXWÍRNÁIEÚÓHÖZBÉOSYGT", "", "Hungarian" },
			{ "GAMMA", "PÚÉÜKEZQÖGIMHALXŐRCJVBÍŰFTUÓOSDNWYÁ", "KZPÓVEBSHJIQÖDLÍWÜÚGNAFOŰTUÁCRŐXMYÉ", "", "Hungarian" }};
}
